# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(413, 296)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(LoginWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 39, 281, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.username_label.setEnabled(True)
        self.username_label.setMinimumSize(QtCore.QSize(50, 0))
        self.username_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.username_label.setStyleSheet("")
        self.username_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label)
        self.username_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.username_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.username_text.setFont(font)
        self.username_text.setObjectName("username_text")
        self.horizontalLayout.addWidget(self.username_text)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.password_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.password_label.setMinimumSize(QtCore.QSize(50, 0))
        self.password_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.password_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_4.addWidget(self.password_label)
        self.password_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password_text.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.password_text.setFont(font)
        self.password_text.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_text.setInputMask("")
        self.password_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_text.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.password_text.setObjectName("password_text")
        self.horizontalLayout_4.addWidget(self.password_text)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.regist_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.regist_btn.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.regist_btn.setFont(font)
        self.regist_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.regist_btn.setStyleSheet("background:transparent;\n"
"color:blue;")
        self.regist_btn.setObjectName("regist_btn")
        self.horizontalLayout_6.addWidget(self.regist_btn)
        self.forget_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.forget_btn.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.forget_btn.setFont(font)
        self.forget_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forget_btn.setStyleSheet("background:transparent;\n"
"color:blue;")
        self.forget_btn.setObjectName("forget_btn")
        self.horizontalLayout_6.addWidget(self.forget_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.login_submit_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.login_submit_btn.setMinimumSize(QtCore.QSize(250, 0))
        self.login_submit_btn.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_submit_btn.setFont(font)
        self.login_submit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_submit_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login_submit_btn.setStyleSheet("color:white;\n"
"border:2px;\n"
"border-radius:10px;\n"
"padding:4px 4px;\n"
"font-size:14pt;\n"
"font-weight:bold;\n"
"background:qlineargradient(x1:0, y1:0, x2:1, y2:0,stop:0 #497BF0,stop:1 #1FB6F6);\n"
"hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #60a3f7, stop:1 #3b78e6);\n"
"}")
        self.login_submit_btn.setObjectName("login_submit_btn")
        self.horizontalLayout_7.addWidget(self.login_submit_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 4)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登录"))
        self.username_label.setText(_translate("LoginWindow", "用户名："))
        self.username_text.setPlaceholderText(_translate("LoginWindow", "请输入用户名"))
        self.password_label.setText(_translate("LoginWindow", "密码："))
        self.password_text.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
        self.regist_btn.setText(_translate("LoginWindow", "新用户注册"))
        self.forget_btn.setText(_translate("LoginWindow", "忘记密码"))
        self.login_submit_btn.setText(_translate("LoginWindow", "登录"))
