experimentName: PMFSNet
searchSpaceFile: search_space.json
trialCommand: python train.py
trialCodeDirectory: ./
experimentWorkingDirectory: ./log
logLevel: info
trialGpuNumber: 1
trialConcurrency: 1
tunerGpuIndices: "1"
maxExperimentDuration: 20d
maxTrialNumber: 50
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True